### ISSUE TITLE
Prompt to save doesn't check for changes in scene config

### ISSUE THREAD

**Issue by jasondkiesling** [engaging-computing/MYR#263]
Steps to reproduce:

1. Open a scene.
2. Change a setting (such as sky color).
3. Close the page.

**Comment by kdvalin** [comment]
Currently in dev, if you move the camera, the browser prompts you if you would like to continue, even if no settings were changed.

This is because the SceneConfigMenu is rendered before the scene is, so it bases the initial settings array off of the default scene passed to it.

I'm not 100% sure why moving the camera is necessary, but debugging traces the problem back to SceneConfigMenu

**Comment by kdvalin** [comment]
PR #382 fixes this
