### ISSUE TITLE
`shrink()` reference is unclear

### ISSUE THREAD

**Issue by kdvalin** [engaging-computing/MYR#517]
**Bug Description:**
The animation function `shrink` does nothing.

**Steps To Reproduce:**
Copy and paste the following code into [learnmyr.org](https://learnmyr.org)
```js
shrink(box());
```

**Expected behavior:**
The box to shrink and grow as the documentation for the animation outlines

**URL(s):**
An example of this bug can be seen [at this scene](https://learnmyr.org/scene/61719bddaf826a0013f5fd2e)

# Platforms the bug occurs on
## Desktop
 - OS: Debian 10
 - Browser: Firefox
 - Version: 92.0.1

**Comment by Jlu18** [comment]
The shrink animation doesn't animate because the magnitude of the animation cursor is 1 by default and the animation is animating the scale current current scale to a value that divide scale by magnitude. Any scale divide by magnitude of 1 is scale, which means scale is changing to same value, so it doesn't have any visual effect.

If you set the magnitude to any value other than 1, you will see the effect.
This also applies to grow.

myr.js, line 1709 
` to: ${el.scale.x / magnitude} ${el.scale.y / magnitude} ${el.scale.z / magnitude};`
